language: php

php:
  - 7
  - 7.1

sudo: false

install: travis_retry composer install

script: composer ci

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
